### ISSUE TITLE
Latest Nuget package throws missing package exception

### ISSUE THREAD

**Issue by Jetski5822** [travcorp/aws-tools#7]
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'CommandLine, Version=1.9.71.2, Culture=neutral, PublicKeyToken=de6f01bd326f8c32' or one of its dependencies. The system cannot find the file specified.
   at AWSPushAndDeploly.Program.Main(String[] args)

**Comment by joshski** [comment]
Latest version doesn't have this issue.
